config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                    Controller#Action
#    categories GET    /categories(.:format)          categories#index
#               POST   /categories(.:format)          categories#create
#  new_category GET    /categories/new(.:format)      categories#new
# edit_category GET    /categories/:id/edit(.:format) categories#edit
#      category GET    /categories/:id(.:format)      categories#show
#               PATCH  /categories/:id(.:format)      categories#update
#               PUT    /categories/:id(.:format)      categories#update
#               DELETE /categories/:id(.:format)      categories#destroy
#       notices GET    /notices(.:format)             notices#index
#               POST   /notices(.:format)             notices#create
#    new_notice GET    /notices/new(.:format)         notices#new
#   edit_notice GET    /notices/:id/edit(.:format)    notices#edit
#        notice GET    /notices/:id(.:format)         notices#show
#               PATCH  /notices/:id(.:format)         notices#update
#               PUT    /notices/:id(.:format)         notices#update
#               DELETE /notices/:id(.:format)         notices#destroy
#          root GET    /                              pages#home
#    edit_users GET    /users/edit(.:format)          users#edit
#         users GET    /users(.:format)               users#index
#               POST   /users(.:format)               users#create
#      new_user GET    /users/new(.:format)           users#new
#          user GET    /users/:id(.:format)           users#show
#               PATCH  /users/:id(.:format)           users#update
#               PUT    /users/:id(.:format)           users#update
#               DELETE /users/:id(.:format)           users#destroy
#         login GET    /login(.:format)               session#new
#               POST   /login(.:format)               session#create
#               DELETE /login(.:format)               session#destroy
#

Rails.application.routes.draw do
   resources :categories
   resources :notices
   root :to => 'pages#home'
   
   resources :users, :except => [:edit] do
    collection do
      get '/edit' => 'users#edit'
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/notice.rb
# == Schema Information
#
# Table name: notices
#
#  id          :integer          not null, primary key
#  heading     :string
#  message     :text
#  category_id :integer
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  cl_id       :string
#  date_from   :datetime
#  date_to     :datetime
#

class Notice < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def index
    @notices = all_or_date
  end

  def new
    @notice = Notice.new
    unless @current_user
      redirect_to '/users/new'
    end
  end

  def create
    @notice = Notice.new notice_params
    @notice.user_id = @current_user.id
    if params[:notice]['file'].present?
      cloudinary = Cloudinary::Uploader.upload(params[:notice]['file'].path)
      @notice.cl_id = cloudinary['public_id']
    end
    if @notice.save
      redirect_to '/notices'
    else
      redirect_to '/notices/new'
    end
  end

  def edit
    @notice = Notice.find params[:id]
  end

  def update 
    notice = Notice.find params[:id]
     if params[:notice]['file'].present?
      cloudinary = Cloudinary::Uploader.upload(params[:notice]['file'].path)
      notice.cl_id = cloudinary['public_id']
    end
    notice.update notice_params
    redirect_to notice
  end

  def show 
    @notice = Notice.find params[:id]
    @user = @notice.user
  end

  def destroy
    notice = Notice.find params[:id]
    notice.destroy
    redirect_to notices_path
  end

  private
  def notice_params
    params.require(:notice).permit(:heading, :message, :category_id, :cl_id, :date_from, :date_to)
  end

   def all_or_date
    today = Time.now
    if params["/notices"]
      id = params["/notices"]["category_id"].to_i
      if id != 0
        @notices = Notice.where("date_from <= :today AND date_to >= :today AND category_id = :id",
          {today: today, id: id})
      else 
        @notices = Notice.where("date_from <= :today AND date_to >= :today",
          {today: today})
      end
    else
       @notices = Notice.where("date_from <= :today AND date_to >= :today",
        {today: today})
    end
  end
 
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<div class="new_notice">
  <%= form_for @notice do |f| %>
    <p>
      <%= f.label :heading %>
      <%= f.text_field :heading, :autofocus => true %>
    </p>

    <p>
      <%= f.label :message %>
      <%= f.text_area :message %>
    </p>

    <p>
      <%= f.label :category_id %>
      <%= f.select :category_id, Category.all.map {|category|[category.name, category.id]}, :include_blank => true %>
    </p>

    <p>
      <%= f.label :Image %>
      <%= f.file_field :file %>
    </p>

    <p>
      <%= f.label :date_from %>
      <%= f.date_field(:date_from, value: Date.today) %>
    </p>

    <p>
      <%= f.label :date_to %>
      <%= f.date_field(:date_to, value: '2015-12-31') %>
    </p>

  <%= f.submit %>
<% end %>
</div>

app/views/notices/_notice.html.erb
 <% if @current_user %>
    <h3><%= link_to('Post New Notice', '/notices/new') %></h3>
  <% end %>
 <ol>
 <% notices.each do |notice| %>
    <li><a href="/notices/<%= notice.id %>">
      <div class="notice_message">
        Notice: <%= notice.heading %><br>
        Details: <%= notice.message %><br>
        User: <%= notice.user.name %> | Category: <% if notice.category %><%= notice.category.name %><% end %><br>
        <% if notice.date_from %>
         Date from: <%= notice.date_from.strftime "%b %d, %Y" %> |
        <% end %>
        <% if notice.date_to %> 
          Date to: <%= notice.date_to.strftime "%b %d, %Y" %><br>
        <% end %>
        <%= cl_image_tag(notice.cl_id) %>
        </div></a>
      
     <% if @current_user && @current_user.admin %>
     <br> <%= link_to('Edit', edit_notice_path(notice)) %>
      <%= button_to('Delete Notice', notice, :method => 'delete', :data => {:confirm => 'You sure homie???'}) %> 
     <% end %>
    </li>
  <% end %>
</ol> 

app/views/notices/edit.html.erb
<h1>Edit Notice</h1>
<%= render :partial => 'form' %>

app/views/notices/index.html.erb
<h2>Notice Board</h2>

  
  <% if @current_user %>
    <h3><%= link_to('Post New Notice', '/notices/new') %></h3>
  <% end %>
<br>
  <p>
    <%= form_for '/notices', :method => "get" do |f| %>
      Select by Category: <%= f.select :category_id, Category.all.map {|category|[category.name, category.id]}, :include_blank => true %>
      <%= f.submit 'Select!' %>
    <% end %> 
  </p>
<br>
<ol>
  <% @notices.each do |notice| %>
    <li><a href="/notices/<%= notice.id %>">
      <div class="notice_message">
        Notice: <%= notice.heading %><br>
        Details: <%= notice.message %><br>
        User: <%= notice.user.name %> | Category: <% if notice.category %><%= notice.category.name %><% end %><br>
        <% if notice.date_from %>
         Date from: <%= notice.date_from.strftime "%b %d, %Y" %> |
        <% end %>
        <% if notice.date_to %> 
          Date to: <%= notice.date_to.strftime "%b %d, %Y" %><br>
        <% end %>
        <%= cl_image_tag(notice.cl_id) %>
        </div></a>
      
     <% if @current_user && @current_user.admin %>
     <br> <%= link_to('Edit', edit_notice_path(notice)) %>
      <%= button_to('Delete Notice', notice, :method => 'delete', :data => {:confirm => 'You sure homie???'}) %> 
     <% end %>
    </li>
  <% end %>
</ol>

app/views/notices/new.html.erb
<h1>New Notice</h1>
<%= render :partial => 'form' %>

app/views/notices/show.html.erb
<div class="notice_message">
<h1><%= @notice.heading %></h1>
  <ul>
    Details: <%= @notice.message %><br> 
    User: <%= @notice.user.name %> |
    Location: <%= @notice.user.address %> |
    Category: <% if @notice.category %><%= @notice.category.name %><% end %><br> 
    
   <% if @notice.date_from %>
    Date from: <%= @notice.date_from.strftime "%b %d, %Y" %>
   <% end %> |
   <% if @notice.date_to %> 
    Date to: <%= @notice.date_to.strftime "%b %d, %Y" %> 
   <% end %>
    <br>
    <%= cl_image_tag(@notice.cl_id) %>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@user.latitude}%2C#{@user.longitude}" %>
</div>
    <% if @current_user %>
      <% if @notice.user_id == @current_user.id || @current_user.admin %>
       <br><%= link_to('Edit', edit_notice_path(@notice)) %>
        <%= button_to('Delete Notice', notice, :method => 'delete', :data => {:confirm => 'You sure homie???'}) %>
      <% end %>
    <% end %>
  </ul> 

  <div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'noticeboardapp';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>