config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                    Controller#Action
#    categories GET    /categories(.:format)          categories#index
#               POST   /categories(.:format)          categories#create
#  new_category GET    /categories/new(.:format)      categories#new
# edit_category GET    /categories/:id/edit(.:format) categories#edit
#      category GET    /categories/:id(.:format)      categories#show
#               PATCH  /categories/:id(.:format)      categories#update
#               PUT    /categories/:id(.:format)      categories#update
#               DELETE /categories/:id(.:format)      categories#destroy
#       notices GET    /notices(.:format)             notices#index
#               POST   /notices(.:format)             notices#create
#    new_notice GET    /notices/new(.:format)         notices#new
#   edit_notice GET    /notices/:id/edit(.:format)    notices#edit
#        notice GET    /notices/:id(.:format)         notices#show
#               PATCH  /notices/:id(.:format)         notices#update
#               PUT    /notices/:id(.:format)         notices#update
#               DELETE /notices/:id(.:format)         notices#destroy
#          root GET    /                              pages#home
#    edit_users GET    /users/edit(.:format)          users#edit
#         users GET    /users(.:format)               users#index
#               POST   /users(.:format)               users#create
#      new_user GET    /users/new(.:format)           users#new
#          user GET    /users/:id(.:format)           users#show
#               PATCH  /users/:id(.:format)           users#update
#               PUT    /users/:id(.:format)           users#update
#               DELETE /users/:id(.:format)           users#destroy
#         login GET    /login(.:format)               session#new
#               POST   /login(.:format)               session#create
#               DELETE /login(.:format)               session#destroy
#

Rails.application.routes.draw do
   resources :categories
   resources :notices
   root :to => 'pages#home'
   
   resources :users, :except => [:edit] do
    collection do
      get '/edit' => 'users#edit'
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href="css/hover.css" rel="stylesheet" media="all">
<link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <title>NoticeboardApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="back_cont">
 <div class="container">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to('Home', root_path) %></li>
      <li><%= link_to('Notices', '/notices') %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to 'All', notices_path %>
          </li>
            <% Category.order('name ASC').each do |category| %>
          <li>
            <%= link_to category.name, category %>
          </li>
            <% end %>
        </ul>
      </li>
      <%== intellinav %>
    </ul>
  </div>
 </div>
 </div>
  </nav>

  <% if flash[:notice].present? %>
    <h3><%= flash[:notice] %></h3>
  <% end %>

  <%= yield %>
 
 </div>
 <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'noticeboardapp';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
</body>
</html>